# YAML是JSON的超集，简洁而强大，引入spring-boot-starter-web依赖间接的引入了
# snakeyaml依赖，snakeyaml会实现 对YAML配置的解析。YAML的使用非常简单，利用缩进来表示层级关系
# 并且大小写敏感。
#
# YAML缺点：无法使用@PropertySource注解加载YAML文件，如果项目有这种需求，还是需要properties格式的
# 文件作为配置文件

# yaml语法配置
server:
  port: 8080
  servlet:
    context-path: /springboot2
  tomcat:
    uri-encoding: utf-8

# 配置自定义属性
my:
  name: 怪侠一枝梅
  address: China
  ## 数组的配置
  favorites:
    - 足球
    - 徒步
    - Coding

## 在集合中存储对象
my1:
  users:
    - name: 张三
      address: China
      favorites:
        - 吃饭
        - 睡觉
        - 打豆豆
    - name: 李四
      address: GZ
      favorites:
        - 读书
        - 看报
        - 运动

